(* ::Package:: *)

PacletObject[
  <|
    "Name" -> "Wolfram/DiagrammaticComputation",
    "Description" -> "Abstract compositional diagrammatic calculus",
    "Creator" -> "Nik Murzin, Ian Ford",
    "License" -> "MIT",
    "PublisherID" -> "Wolfram",
    "Version" -> "1.0.8",
    "WolframVersion" -> "15.0+",
    "PrimaryContext" -> "Wolfram`DiagrammaticComputation`",
    "Dependencies" -> {"WolframInstitute/Hypergraph"},
    "Extensions" -> {
      {
        "Kernel",
        "Root" -> "Kernel",
        "Context" -> {"Wolfram`DiagrammaticComputation`"},
        "Symbols" -> {
          "Wolfram`DiagrammaticComputation`AnnihilationRule",
          "Wolfram`DiagrammaticComputation`CapDiagram",
          "Wolfram`DiagrammaticComputation`ColumnDiagram",
          "Wolfram`DiagrammaticComputation`CommutationRule",
          "Wolfram`DiagrammaticComputation`CopyDiagram",
          "Wolfram`DiagrammaticComputation`CupDiagram",
          "Wolfram`DiagrammaticComputation`Diagram",
          "Wolfram`DiagrammaticComputation`DiagramArrange",
          "Wolfram`DiagrammaticComputation`DiagramAssignPorts",
          "Wolfram`DiagrammaticComputation`DiagramCases",
          "Wolfram`DiagrammaticComputation`DiagramComposition",
          "Wolfram`DiagrammaticComputation`DiagramCopySplit",
          "Wolfram`DiagrammaticComputation`DiagramDecompose",
          "Wolfram`DiagrammaticComputation`DiagramDelete",
          "Wolfram`DiagrammaticComputation`DiagramDraw",
          "Wolfram`DiagrammaticComputation`DiagramDual",
          "Wolfram`DiagrammaticComputation`DiagramExpressionReplace",
          "Wolfram`DiagrammaticComputation`DiagramExtract",
          "Wolfram`DiagrammaticComputation`DiagramFlip",
          "Wolfram`DiagrammaticComputation`DiagramFunction",
          "Wolfram`DiagrammaticComputation`DiagramGraphSimplify",
          "Wolfram`DiagrammaticComputation`DiagramGraphics",
          "Wolfram`DiagrammaticComputation`DiagramGrid",
          "Wolfram`DiagrammaticComputation`DiagramGridHeight",
          "Wolfram`DiagrammaticComputation`DiagramGridTree",
          "Wolfram`DiagrammaticComputation`DiagramGridWidth",
          "Wolfram`DiagrammaticComputation`DiagramGridWidthHeight",
          "Wolfram`DiagrammaticComputation`DiagramHypergraph",
          "Wolfram`DiagrammaticComputation`DiagramHypergraphRule",
          "Wolfram`DiagrammaticComputation`DiagramInsert",
          "Wolfram`DiagrammaticComputation`DiagramMap",
          "Wolfram`DiagrammaticComputation`DiagramMapAt",
          "Wolfram`DiagrammaticComputation`DiagramMatchPorts",
          "Wolfram`DiagrammaticComputation`DiagramNestReplace",
          "Wolfram`DiagrammaticComputation`DiagramNetwork",
          "Wolfram`DiagrammaticComputation`DiagramPattern",
          "Wolfram`DiagrammaticComputation`DiagramPermute",
          "Wolfram`DiagrammaticComputation`DiagramPosition",
          "Wolfram`DiagrammaticComputation`DiagramPositions",
          "Wolfram`DiagrammaticComputation`DiagramProduct",
          "Wolfram`DiagrammaticComputation`DiagramQ",
          "Wolfram`DiagrammaticComputation`DiagramReplace",
          "Wolfram`DiagrammaticComputation`DiagramReplaceList",
          "Wolfram`DiagrammaticComputation`DiagramReplacePart",
          "Wolfram`DiagrammaticComputation`DiagramReverse",
          "Wolfram`DiagrammaticComputation`DiagramRightComposition",
          "Wolfram`DiagrammaticComputation`DiagramRule",
          "Wolfram`DiagrammaticComputation`DiagramSplit",
          "Wolfram`DiagrammaticComputation`DiagramSubdiagrams",
          "Wolfram`DiagrammaticComputation`DiagramSum",
          "Wolfram`DiagrammaticComputation`DiagramTensor",
          "Wolfram`DiagrammaticComputation`DiagramsFreePorts",
          "Wolfram`DiagrammaticComputation`DiagramsGraph",
          "Wolfram`DiagrammaticComputation`DiagramsNetGraph",
          "Wolfram`DiagrammaticComputation`DiagramsPortGraph",
          "Wolfram`DiagrammaticComputation`DuplicateAnnihilationRule",
          "Wolfram`DiagrammaticComputation`DuplicateEraserRule",
          "Wolfram`DiagrammaticComputation`EmptyDiagram",
          "Wolfram`DiagrammaticComputation`EmptyDiagramQ",
          "Wolfram`DiagrammaticComputation`EmptyPortQ",
          "Wolfram`DiagrammaticComputation`EraserAnnihilationRule",
          "Wolfram`DiagrammaticComputation`EraserDiagram",
          "Wolfram`DiagrammaticComputation`EraserRule",
          "Wolfram`DiagrammaticComputation`FeynArtsTopologyGraphics",
          "Wolfram`DiagrammaticComputation`FeynmanDiagram",
          "Wolfram`DiagrammaticComputation`GridInputPorts",
          "Wolfram`DiagrammaticComputation`GridOutputPorts",
          "Wolfram`DiagrammaticComputation`IdentityDiagram",
          "Wolfram`DiagrammaticComputation`MergeDiagram",
          "Wolfram`DiagrammaticComputation`PermutationDiagram",
          "Wolfram`DiagrammaticComputation`Port",
          "Wolfram`DiagrammaticComputation`PortDual",
          "Wolfram`DiagrammaticComputation`PortMinus",
          "Wolfram`DiagrammaticComputation`PortNeutral",
          "Wolfram`DiagrammaticComputation`PortPower",
          "Wolfram`DiagrammaticComputation`PortProduct",
          "Wolfram`DiagrammaticComputation`PortQ",
          "Wolfram`DiagrammaticComputation`PortSum",
          "Wolfram`DiagrammaticComputation`PropagationRule",
          "Wolfram`DiagrammaticComputation`RemoveDiagramRule",
          "Wolfram`DiagrammaticComputation`RowDiagram",
          "Wolfram`DiagrammaticComputation`SimplifyDiagram",
          "Wolfram`DiagrammaticComputation`SingletonDiagram",
          "Wolfram`DiagrammaticComputation`SpiderDiagram",
          "Wolfram`DiagrammaticComputation`TagPort",
          "Wolfram`DiagrammaticComputation`TensorDiagram",
          "Wolfram`DiagrammaticComputation`ToDiagram",
          "Wolfram`DiagrammaticComputation`ToDiagramNetwork",
          "Wolfram`DiagrammaticComputation`TopologyGraph",
          "Wolfram`DiagrammaticComputation`TopologyGraphics",
          "Wolfram`DiagrammaticComputation`TopologyGraphs",
          "Wolfram`DiagrammaticComputation`UntagPort",
          "Wolfram`DiagrammaticComputation`WigglyArcFunction",
          "Wolfram`DiagrammaticComputation`ZeroDiagram",
          "Wolfram`DiagrammaticComputation`ZeroPortQ"
        }
      },
      {"Documentation", "Language" -> "English"}
    }
  |>
]
